name: Upload Image (GCP)
description: "Uploads a Docker image to a GCP Artifact Registry."
inputs:
  credentials:
    description: "Service Account Credentials"
    required: true
  registry:
    description: "Artifact Registry Domain"
    required: true
    default: europe-west1-docker.pkg.dev
  image:
    description: "Build and push the image, if provided"
    required: false
  directory:
    description: "Directory to build the image in."
    required: false
    default: "."
  skipAuth:
    description: "Skip authentication, if provided"
    required: false
runs:
  using: "composite"
  steps:
    - name: GCP Authentication
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ inputs.credentials }}
      if: "! ${{ inputs.skipAuth }}"

    - name: Setup Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      if: "! ${{ inputs.skipAuth }}"

    - name: Setup Docker Registry
      shell: bash
      run: "gcloud auth configure-docker ${{ inputs.registry }} --quiet"
      if: "! ${{ inputs.skipAuth }}"

    - name: Build Image
      shell: bash
      run: "docker build --platform linux/amd64 -t ${{ inputs.registry }}/${{ inputs.image }}:${GITHUB_SHA::7} ."
      if: "${{ inputs.image }}"
      working-directory: "${{ inputs.directory }}"

    - name: Push Image
      shell: bash
      run: "docker push ${{ inputs.registry }}/${{ inputs.image }}:${GITHUB_SHA::7}"
      if: "${{ inputs.image }}"
