name: Test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 30
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Stack
        uses: ./setup-stack
        with:
          directory: "example"
          ghp-token: "foo"

      - name: Run Node
        run: node main.js
        working-directory: example

      - name: Run Go
        run: go run main.go
        working-directory: example
