name: Test

on:
  push:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    timeout-minutes: 30
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Stack
        uses: ./setup-stack
        with:
          directory: "example"
          ghp-token: "foo"

      - name: Run Node
        run: "node main.js"
        working-directory: example

      - name: Run Go
        run: "go run main.go"
        working-directory: example

      - name: Upload Image (GCP)
        uses: ./upload-image-gcp
        with:
          credentials: "${{ secrets.GCP_AR_KEY }}"
          image: "sternenbauer/galaxy/actions-example"
          directory: "example"

      - name: Update Deployment
        uses: ./update-deployment
        with:
          k8s-config: "${{ secrets.K8S_CONFIG }}"
          deployment: "actions-example"
          container: "actions-example"
          image: "sternenbauer/galaxy/actions-example"
